### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by mschwaig** [tadfisher/nix-dart#2]
I tried building a flutter app with this project, which does not seem to work.

I wanted to share my notes here in case that is helpful.

I tried building https://github.com/GreenPassApp/greenpass-app as a flake with this project.

It seem like dependencies from the flutter SDK end up in the `pubspec.yml` like this
```
  flutter_web_plugins:
    dependency: transitive
    description: flutter
    source: sdk
    version: 0.0.0
```
while regular dependencies look like this
```
  app_settings:
    dependency: "direct main"
    description:
      name: app_settings
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.1.1"
```

The description containing text and not a name and a URL make ``pub2nix`` trip and stop adding hashes to `pub2nix.lock` after encountering the first such dependency.

I think `pub2nix` can only deal with dependencies of type `hosted`(the regular most common case) while the types `sdk` and `git` would probably have to be handled differently in `nix-dart` here and in `pub2nix`.

I am not sure what else would have to be done to get flutter apps building. It seems flutter would have to be invoked instead of dart.

I saw that there is also flutter support in `nixpkgs` (See https://github.com/NixOS/nixpkgs/issues/36759#issuecomment-578422986), but I have not looked more closely at that because I am unsure if there is a good way to get dependencies into a sandboxed build that way.

I am not actively working on getting this to work anymore as of now, since it was just an experiment for me. I am also not that familiar with flutter or dart.
